@echo off
echo Setting up Frontend...
cd frontend
echo Installing dependencies...
call npm install
echo Building project...
call npm run build
echo Initializing Capacitor...
call npx cap init RemoveBG com.removebg.ai --web-dir=dist
echo Adding Android platform...
call npx cap add android
echo Setup Complete!
echo To run backend: ..\run_backend.bat
echo To open Android Studio: cd frontend && npx cap open android
pause
